Repository ItsZil/investiciju-portfolio, pull requests merged in 2022-05, with the labels that each got.

#10 IP-31-create-settings-tab-design
  Classes/FlatComboBox.cs
  HomeWindow.Designer.cs
  HomeWindow.cs
  LoginForm.cs
  OverviewTab.Designer.cs
  OverviewTab.cs
  SettingsTab.Designer.cs
  SettingsTab.cs
  SettingsTab.resx
  investiciju-portfolio.csproj
Labels: frontend

#11 Implement setting saving and loading
  App.config
  Classes/Login.cs
  Forms/HomeWindow.Designer.cs
  Forms/HomeWindow.cs
  Forms/HomeWindow.resx
  Forms/LoginForm.Designer.cs
  Forms/LoginForm.cs
  Forms/LoginForm.resx
  Forms/OverviewTab.Designer.cs
  Forms/OverviewTab.cs
  Forms/OverviewTab.resx
  Forms/RegistrationForm.Designer.cs
  Forms/RegistrationForm.cs
  Forms/RegistrationForm.resx
  Forms/SettingsTab.Designer.cs
  Forms/SettingsTab.cs
  Forms/SettingsTab.resx
  Program.cs
  Properties/Settings.Designer.cs
  Properties/Settings.settings
  Settings.settings
  SettingsTab.cs
  Utilities/SettingsHandler.cs
  investiciju-portfolio.csproj
Labels: backend

#15 IP-40-create-back-buttons-for-navigation
  Forms/RegistrationForm.Designer.cs
  Forms/RegistrationForm.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/LeftArrow30px.png
  investiciju-portfolio.csproj
Labels: frontend

#14 IP-42-implement-create-edit-and-delete-instrument-buttons
  App.config
  Forms/HomeWindow.Designer.cs
  Forms/OverviewTab.Designer.cs
  Forms/OverviewTab.cs
  Forms/RegistrationForm.Designer.cs
  Forms/RegistrationForm.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/LeftArrow30px.png
  Resources/close15px.png
  Utilities/ApiHelper.cs
  investiciju-portfolio.csproj
  packages.config
Labels: frontend

#12 Implement password change functionality
  Classes/Login.cs
  Classes/Registration.cs
  Forms/SettingsTab.Designer.cs
  Forms/SettingsTab.cs
  Utilities/PasswordHandler.cs
Labels: backend, frontend

#19 Implemented stock deletion button functionality
  Classes/Creation.cs
  Forms/OverviewTab.cs
  Utilities/StockHandler.cs
  investiciju-portfolio.csproj
Labels: backend

#21 Create chart of previous 7 day portfolio value
  Forms/OverviewTab.Designer.cs
  Forms/OverviewTab.cs
  Utilities/EquityHandler.cs
  Utilities/StockAPI.cs
  investiciju-portfolio.csproj
Labels: backend

#22 IP-40-create-back-buttons-for-navigation
  Forms/OverviewTab.Designer.cs
  Forms/RegistrationForm.Designer.cs
  Forms/RegistrationForm.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/LeftArrow30px.png
  investiciju-portfolio.csproj
Labels: frontend
